version: "3.9"
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: react-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app
    networks:
      - network
networks:
  network: